### ISSUE TITLE
Kazas - garbage room, walking towards garbage platform from left side while it's down causes script read out of bounds

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Severed-Chains#1078]
```
java.lang.RuntimeException: An error occurred while ticking script 10
	at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:206)
	at legend.game.scripting.ScriptManager.tick(ScriptManager.java:41)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:411)
	at legend.core.RenderEngine.lambda$init$24(RenderEngine.java:495)
	at legend.core.opengl.Window$Events.onDraw(Window.java:672)
	at legend.core.opengl.Window.tickFrame(Window.java:312)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:289)
	at legend.core.RenderEngine.run(RenderEngine.java:998)
	at legend.core.GameEngine.start(GameEngine.java:236)
	at legend.game.Main.main(Main.java:23)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2535 out of bounds for length 2535
	at legend.game.scripting.ScriptFile.getOp(ScriptFile.java:25)
	at legend.game.scripting.ScriptInlineParam.get(ScriptInlineParam.java:26)
	at legend.game.scripting.ScriptState.scriptMove(ScriptState.java:652)
	at legend.game.scripting.ScriptState.runOp(ScriptState.java:505)
	at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:471)
	at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:180)
	... 11 more
```

**Comment by avionanx** [comment]
Extending LABEL_82 with -1 seems to fix it. Script has a check for -1 but there is no -1 in the table, so inline parameter overflows. Broken in RB2.1, retail script bug.

**Comment by avionanx** [comment]
There are decompilation warnings, compiling with said fix breaks other stuff like interacting with the NPC in that submap.

**Comment by LordMonoxide** [comment]
DRGN1/597/1

**Comment by avionanx** [comment]
Pressing both up and down or left and right at the same time or any input combination not in this table causes the issue.
```
LABEL_82:
data 0x1000
data 0x3000
data 0x2000
data 0x6000
data 0x4000
data 0xc000
data 0x8000
data 0x9000

**Comment by avionanx** [comment]
Also DRGN22/597/1
