### ISSUE TITLE
Rare Starting Crash

### ISSUE THREAD

**Issue by avionanx** [Legend-of-Dragoon-Modding/Severed-Chains#1123]
Happens sometimes when game is just loaded

```
19:52:30.108 [Hardware legend.core.GameEngine:243] INFO : Booting mods...
19:52:30.109 [Hardware legend.core.GameEngine:250] INFO : Loading mods [lod, lod-core]...
19:52:30.109 [Hardware org.legendofdragoon.modloader.ModManager:131] INFO : Loaded mod: lod
19:52:30.109 [Hardware org.legendofdragoon.modloader.ModManager:131] INFO : Loaded mod: lod-core
19:52:30.111 [Hardware org.legendofdragoon.modloader.events.EventManager:35] INFO : Scanning for event consumers...
19:52:30.333 [Hardware legend.core.RenderEngine:1006] ERROR: Shutting down due to exception:
java.lang.NullPointerException: Cannot invoke "legend.game.types.UiFile.uiElements_0000()" because "legend.game.Scus94491BpeSegment_800b.uiFile_800bdc3c" is null
	at legend.game.Scus94491BpeSegment_8002.allocateManualRenderable(Scus94491BpeSegment_8002.java:1324)
	at legend.game.inventory.screens.controls.Background.<init>(Background.java:19)
	at legend.game.inventory.screens.LoadGameScreen.<init>(LoadGameScreen.java:33)
	at legend.game.inventory.screens.CampaignSelectionScreen.lambda$onSelection$3(CampaignSelectionScreen.java:72)
	at legend.game.inventory.screens.CampaignSelectionScreen.onSelection(CampaignSelectionScreen.java:101)
	at legend.game.inventory.screens.controls.BigList.lambda$addLabel$1(BigList.java:68)
	at legend.game.inventory.screens.Control.mouseClick(Control.java:300)
	at legend.game.inventory.screens.ControlHost.mouseClick(ControlHost.java:128)
	at legend.game.inventory.screens.Control.mouseClick(Control.java:295)
	at legend.game.inventory.screens.ControlHost.mouseClick(ControlHost.java:128)
	at legend.game.inventory.screens.MenuScreen.mouseClick(MenuScreen.java:87)
	at legend.game.inventory.screens.MenuStack.lambda$mouseRelease$2(MenuStack.java:193)
	at legend.game.inventory.screens.MenuStack.propagate(MenuStack.java:110)
	at legend.game.inventory.screens.MenuStack.input(MenuStack.java:102)
	at legend.game.inventory.screens.MenuStack.mouseRelease(MenuStack.java:193)
	at legend.core.opengl.Window$Events.lambda$onMouseButton$9(Window.java:445)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at legend.core.opengl.Window$Events.onMouseButton(Window.java:445)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at legend.core.opengl.Window.tickInput(Window.java:306)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:289)
	at legend.core.RenderEngine.run(RenderEngine.java:1004)
	at legend.core.GameEngine.start(GameEngine.java:236)
	at legend.game.Main.main(Main.java:23)
19:52:30.337 [Hardware legend.core.opengl.Window:98] INFO : Shutting down...

**Comment by DrewUniverse** [comment]
Just got this. Happened during alt-tab back to windowed client.
