### ISSUE TITLE
Forest of Winglies issue loading next area to progress; seeing Ancestor Blano. (Impedes any further progress in game)

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1125]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/27cc19d6-2a42-4641-ae2e-eadf6548616b

`Exception in thread "pool-2-thread-8" java.lang.NullPointerException: Cannot invoke "legend.game.unpacker.FileData.realFileIndex()" because the return value of "java.util.List.get(int)" is null
	at legend.game.submap.RetailSubmap.prepareSobjs(RetailSubmap.java:482)
	at legend.game.submap.RetailSubmap.lambda$loadAssets$4(RetailSubmap.java:208)
	at legend.core.Async.allLoaded(Async.java:9)
	at legend.game.submap.RetailSubmap.lambda$loadAssets$5(RetailSubmap.java:209)
	at legend.core.Async.allLoaded(Async.java:12)
	at legend.game.submap.RetailSubmap.lambda$loadAssets$7(RetailSubmap.java:211)
	at legend.game.unpacker.Unpacker.lambda$loadDirectory$5(Unpacker.java:195)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)`

As of commit https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/af4cf92c302859d22ea5280b7a65ca26144be7c9

**Comment by LordMonoxide** [comment]
Looking like this may be an issue with the MRG file, entry 16 is missing the symlink destination
`16=;0`

**Comment by LordMonoxide** [comment]
Looks like this happens if it fails to find the texture during unpacking:
```
12:47:46.352 [Thread-1 legend.game.unpacker.SubmapPxlTransformer:105] WARN : Failed to find texture for SECT/DRGN23.BIN/173 sobj 16
```
