### ISSUE TITLE
Error on start up using recommended build #2

### ISSUE THREAD

**Issue by Toteas** [Legend-of-Dragoon-Modding/Severed-Chains#1141]
[Hardware legend.core.gpu.Gpu:148] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: Failed to create texture, glError: 500
        at legend.core.opengl.Texture.<init>(Texture.java:101)
        at legend.core.opengl.Texture$Builder.build(Texture.java:257)
        at legend.core.opengl.Texture.create(Texture.java:49)
        at legend.core.opengl.Texture.empty(Texture.java:55)
        at legend.core.gpu.Gpu.displaySize(Gpu.java:524)
        at legend.core.gpu.Gpu.rescaleNow(Gpu.java:129)
        at legend.game.fmv.Fmv.play(Fmv.java:247)
        at legend.game.fmv.Fmv.playCurrentFmv(Fmv.java:217)
        at legend.core.GameEngine.transitionToGame(GameEngine.java:389)
        at legend.core.GameEngine.renderIntro(GameEngine.java:491)
        at legend.core.gpu.Gpu.lambda$init$3(Gpu.java:222)
        at legend.core.opengl.Context.draw(Context.java:91)
        at legend.core.opengl.Window$Events.onDraw(Window.java:653)
        at legend.core.opengl.Window.tickFrame(Window.java:294)
        at legend.core.opengl.Action.run(Action.java:46)
        at legend.core.opengl.Action.tick(Action.java:32)
        at legend.core.opengl.Window.run(Window.java:271)
        at legend.core.gpu.Gpu.run(Gpu.java:146)
        at legend.core.GameEngine.start(GameEngine.java:225)
        at legend.game.Main.main(Main.java:23)
        at legend.game.MainWindows.main(MainWindows.java:33)

**Comment by LordMonoxide** [comment]
Hi Toteas, are you in our Discord server? I'd like to talk to you directly about this issue to gather some info

**Comment by Toteas** [comment]
Hi Corey, I just joined the discord now on discord I am evilwolfsage. Sorry
it took so long to reply, I work graveyard shifts in the week.

**Comment by LordMonoxide** [comment]
We've been doing some digging and this is being caused by another program injecting legacy OpenGL commands into SC. See this issue for more details: https://github.com/OpenRA/OpenRA/issues/18047

Toteas is going to try to determine what program is doing it so we can file a report with them.

**Comment by LordMonoxide** [comment]
The problematic program in this case was GPU Tweak III. Other programs that can do this are MSI AfterBurner, the Discord overlay, RivaTuner, and others.
