### ISSUE TITLE
Divine dragoon d-attack crash

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Severed-Chains#1183]
```
java.lang.ArrayIndexOutOfBoundsException: Index 18 out of bounds for length 17
	at legend.game.combat.effects.WeaponTrailEffect3c.getVertexMinMaxByComponent(WeaponTrailEffect3c.java:50)
	at legend.game.combat.effects.WeaponTrailEffect3c.tickWeaponTrailEffect(WeaponTrailEffect3c.java:185)
	at legend.game.combat.SEffe.effectManagerTicker(SEffe.java:855)
	at legend.game.scripting.ScriptState.tick(ScriptState.java:179)
	at legend.game.scripting.ScriptManager.executeScriptTickers(ScriptManager.java:225)
	at legend.game.scripting.ScriptManager.tick(ScriptManager.java:48)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:414)
	at legend.core.RenderEngine.lambda$init$16(RenderEngine.java:449)
	at legend.core.opengl.Window$Events.onDraw(Window.java:697)
	at legend.core.opengl.Window.tickFrame(Window.java:337)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:314)
	at legend.core.RenderEngine.run(RenderEngine.java:927)
	at legend.core.GameEngine.start(GameEngine.java:241)
	at legend.game.Main.main(Main.java:23)
```

**Comment by LordMonoxide** [comment]
This is no longer happening
