### ISSUE TITLE
Save Files modified in Notepad causes crash

### ISSUE THREAD

**Issue by Chocolate06** [Legend-of-Dragoon-Modding/Severed-Chains#1554]
11:06:30.920 [Hardware legend.core.RenderEngine:1123] ERROR: Shutting down due to exception:
java.lang.IndexOutOfBoundsException: Read end 2105360 out of bounds 1060
        at legend.game.unpacker.FileData.checkBounds(FileData.java:223)
        at legend.game.unpacker.FileData.readAscii(FileData.java:147)
        at legend.game.unpacker.FileData.readAscii(FileData.java:141)
        at legend.game.saves.serializers.V3Serializer.fromV3(V3Serializer.java:29)
        at legend.game.saves.SaveManager.loadGame(SaveManager.java:392)
        at legend.game.saves.SaveManager.loadGame(SaveManager.java:383)
        at legend.game.saves.SaveManager.loadAllSaves(SaveManager.java:434)
        at legend.game.saves.SaveManager.loadAllCampaigns(SaveManager.java:408)
        at legend.game.inventory.screens.CampaignSelectionScreen.<init>(CampaignSelectionScreen.java:67)
        at legend.game.Scus94491BpeSegment_8002.loadAndRenderMenus(Scus94491BpeSegment_8002.java:874)
        at legend.game.title.Ttle.fadeOutToMenu(Ttle.java:396)
        at legend.game.title.Ttle.waitForSaveSelection(Ttle.java:438)
        at legend.game.title.Ttle.tick(Ttle.java:150)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:412)
        at legend.core.RenderEngine.lambda$init$17(RenderEngine.java:494)
        at legend.core.opengl.Window$Events.onDraw(Window.java:697)
        at legend.core.opengl.Window.tickFrame(Window.java:337)
        at legend.core.opengl.Action.run(Action.java:46)
        at legend.core.opengl.Action.tick(Action.java:32)
        at legend.core.opengl.Window.run(Window.java:314)
        at legend.core.RenderEngine.run(RenderEngine.java:1121)
        at legend.core.GameEngine.start(GameEngine.java:251)
        at legend.game.Main.main(Main.java:23)
        at legend.game.MainWindows.main(MainWindows.java:33)

Fruegal file is an older save, break test should be a current save

[save crash.zip](https://github.com/user-attachments/files/16574152/save.crash.zip)

**Comment by LordMonoxide** [comment]
[save_1.zip](https://github.com/user-attachments/files/17693825/save_1.zip)

Here's a save with an invalid equipment id which also crashes the game

**Comment by aharonphytech** [comment]
I'll look into that
