### ISSUE TITLE
Crash at vertical layout screen

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Severed-Chains#1605]
While navigating settings screen for new campaign, sudden crash. Was using Wiimote - movement triggers one or more keybinds, which I believe caused the crash.

```18:06:16.081 [Hardware legend.game.saves.ConfigStorage:47] INFO : Saving config GLOBAL to config.dcnf
18:06:16.081 [Hardware legend.game.saves.ConfigStorage:127] WARN : Unknown config ID lod_core:controller_keybinds
18:06:29.113 [Hardware legend.core.RenderEngine:1123] ERROR: Shutting down due to exception:
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at legend.game.inventory.screens.VerticalLayoutScreen.highlightRow(VerticalLayoutScreen.java:76)
	at legend.game.inventory.screens.VerticalLayoutScreen.mouseMove(VerticalLayoutScreen.java:131)
	at legend.game.inventory.screens.MenuStack.lambda$mouseMove$1(MenuStack.java:172)
	at legend.game.inventory.screens.MenuStack.propagate(MenuStack.java:116)
	at legend.game.inventory.screens.MenuStack.input(MenuStack.java:108)
	at legend.game.inventory.screens.MenuStack.mouseMove(MenuStack.java:172)
	at legend.core.opengl.Window$Events.lambda$onMouseMove$7(Window.java:462)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at legend.core.opengl.Window$Events.onMouseMove(Window.java:462)
	at org.lwjgl.glfw.GLFWCursorPosCallbackI.callback(GLFWCursorPosCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at legend.core.opengl.Window.tickInput(Window.java:331)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:314)
	at legend.core.RenderEngine.run(RenderEngine.java:1121)
	at legend.core.GameEngine.start(GameEngine.java:251)
	at legend.game.Main.main(Main.java:23)
```

**Comment by DrewUniverse** [comment]
I think I got a reproduction of the issue. Crash when navigating to New Campaign > Mods.

```22:55:15.865 [Hardware legend.game.saves.ConfigStorage:47] INFO : Saving config GLOBAL to config.dcnf
22:55:15.865 [Hardware legend.game.saves.ConfigStorage:127] WARN : Unknown config ID lod_core:controller_keybinds
22:55:18.166 [Hardware legend.core.RenderEngine:1123] ERROR: Shutting down due to exception:
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at legend.game.inventory.screens.VerticalLayoutScreen.highlightRow(VerticalLayoutScreen.java:76)
	at legend.game.inventory.screens.VerticalLayoutScreen.pressedWithRepeatPulse(VerticalLayoutScreen.java:207)
	at legend.game.inventory.screens.MenuStack.lambda$pressedWithRepeatPulse$7(MenuStack.java:231)
	at legend.game.inventory.screens.MenuStack.propagate(MenuStack.java:116)
	at legend.game.inventory.screens.MenuStack.input(MenuStack.java:108)
	at legend.game.inventory.screens.MenuStack.pressedWithRepeatPulse(MenuStack.java:231)
	at legend.core.opengl.Window$Events.lambda$onInputPressedWithRepeat$13(Window.java:495)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at legend.core.opengl.Window$Events.onInputPressedWithRepeat(Window.java:495)
	at legend.core.opengl.Window$Events.callInputEvents(Window.java:504)
	at legend.game.input.Input.update(Input.java:65)
	at legend.core.opengl.Window.tickInput(Window.java:332)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:314)
	at legend.core.RenderEngine.run(RenderEngine.java:1121)
	at legend.core.GameEngine.start(GameEngine.java:251)
	at legend.game.Main.main(Main.java:23)
```
