### ISSUE TITLE
Crash when Struck by Thunder Arrow

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains#1704]
**Describe the bug**
Game crashed when Haschel was hit by Thunder Arrow. This could be an issue with Thunder Arrow itself, or it might be an issue with the status effect immunity animation since TA inflicts stun but Haschel was guarding rendering him immune.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/170744536/3caf1763-034b-468f-a4da-ab707c48b19c

![Crash Log for Archer](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/170744536/d2777fcc-e565-4e9e-b875-6dfe54acaedc)

**Comment by ameyer117** [comment]
Same issue as others, I'm using the latest dev build:
```
java.lang.IllegalArgumentException
	at org.joml.MemUtil$MemUtilNIO.set(MemUtil.java:2803)
	at org.joml.Matrix3f.set(Matrix3f.java:3251)
	at legend.game.combat.SEffe.renderThunderArrowEffect(SEffe.java:1089)
	at legend.game.scripting.ScriptState.render(ScriptState.java:205)
	at legend.game.scripting.ScriptManager.executeScriptRenderers(ScriptManager.java:248)
	at legend.game.scripting.ScriptManager.tick(ScriptManager.java:72)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:423)
	at legend.core.RenderEngine.lambda$init$17(RenderEngine.java:504)
	at legend.core.opengl.Window$Events.onDraw(Window.java:697)
	at legend.core.opengl.Window.tickFrame(Window.java:337)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:314)
	at legend.core.RenderEngine.run(RenderEngine.java:1131)
	at legend.core.GameEngine.start(GameEngine.java:251)
	at legend.game.Main.main(Main.java:24)
	```

**Comment by avionanx** [comment]
RTX3050
```
23:38:46.119 [Hardware legend.game.Main:64] ERROR: ----------------------------------------------------------------------------
23:38:46.120 [Hardware legend.game.Main:65] ERROR: Crash detected
23:38:46.120 [Hardware legend.game.Main:66] ERROR: Severed Chains 3.0.0-1178-beta commit 611b50a296c0c13787fc3fac0cb01cd8832ab631 built 2025-02-19T12:36:27Z
23:38:46.120 [Hardware legend.game.Main:69] ERROR: We have attempted to generate a recovery save. You can load it next time you run Severed Chains.
23:38:46.120 [Hardware legend.game.Main:72] ERROR: Please copy this crash log and send it to us in the Player Help channel in the Legend of Dragoon Discord server.
23:38:46.120 [Hardware legend.game.Main:73] ERROR: https://discord.gg/legendofdragoon
23:38:46.121 [Hardware legend.game.Main:76] ERROR: Message: Cannot invoke "org.joml.Vector3ic.x()" because "v" is null
23:38:46.121 [Hardware legend.game.Main:79] ERROR: ----------------------------------------------------------------------------
23:38:46.121 [Hardware legend.game.Main:80] ERROR: Stack trace:
java.lang.NullPointerException: Cannot invoke "org.joml.Vector3ic.x()" because "v" is null
        at org.joml.Vector3i.sub(Vector3i.java:688)
        at org.joml.Vector3i.sub(Vector3i.java:684)
        at legend.game.combat.SEffe.tickThunderArrowEffect(SEffe.java:1107)
        at legend.game.scripting.ScriptState.tick(ScriptState.java:191)
        at legend.game.scripting.ScriptManager.executeScriptTickers(ScriptManager.java:224)
        at legend.game.scripting.ScriptManager.tick(ScriptManager.java:70)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$46(Scus94491BpeSegment.java:418)
        at legend.core.RenderEngine.lambda$init$18(RenderEngine.java:609)
        at legend.core.opengl.Window$Events.onDraw(Window.java:792)
        at legend.core.opengl.Window.tickFrame(Window.java:432)
        at legend.core.opengl.Action.run(Action.java:46)
        at legend.core.opengl.Action.tick(Action.java:32)
        at legend.core.opengl.Window.run(Window.java:408)
        at legend.core.RenderEngine.run(RenderEngine.java:1008)
        at legend.core.GameEngine.start(GameEngine.java:256)
        at legend.game.Main.main(Main.java:40)
        at legend.game.MainWindows.main(MainWindows.java:38)
23:38:46.124 [Hardware legend.game.Main:82] ERROR: Please copy this crash log and send it to us in the Player Help channel in the Legend of Dragoon Discord server.
23:38:46.124 [Hardware legend.game.Main:83] ERROR: https://discord.gg/legendofdragoon
Press any key to continue . . .
```

**Comment by avionanx** [comment]
```
00:11:38.697 [pool-2-thread-12 legend.game.combat.Battle:6051] INFO : Loading DEFF script
00:11:38.697 [pool-2-thread-12 legend.game.unpacker.Loader:61] INFO : File .\files\SECT\DRGN0.BIN\4632\1 loaded (remaining queued: 0)
00:11:38.737 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script .\files\SECT\DRGN0.BIN\4632 into index 15 (entry point 0x1)
00:11:38.788 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 13 (Empty EffectManager child, allocated by script 15 (DEFF ticker for script 12 (Enemy combatant index 1)) from scriptAllocateEmptyEffectManagerChild)
00:11:38.788 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Do nothing into index 13 (entry point 0x0)
00:11:38.788 [Hardware legend.game.combat.SEffe:582] INFO : Allocating empty effect manager 13 (parent: 15) from legend.game.combat.SEffe.allocateEffectManager(SEffe.java:558)
00:11:38.788 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script .\files\SECT\DRGN0.BIN\4632 into index 13 (entry point 0x0)
00:11:38.838 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 16 (DEFF TMD DEFF index 5 (flags 03010201))
00:11:38.838 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Do nothing into index 16 (entry point 0x0)
00:11:38.838 [Hardware legend.game.combat.SEffe:580] INFO : Allocating effect manager 16 for DeffTmdRenderer14 (parent: 13) from legend.game.combat.SEffe.allocateDeffTmd(SEffe.java:4363)
00:11:38.838 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 23 (Empty EffectManager child, allocated by script 15 (DEFF ticker for script 12 (Enemy combatant index 1)) from scriptAllocateEmptyEffectManagerChild)
00:11:38.838 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Do nothing into index 23 (entry point 0x0)
00:11:38.838 [Hardware legend.game.combat.SEffe:582] INFO : Allocating empty effect manager 23 (parent: 15) from legend.game.combat.SEffe.allocateEffectManager(SEffe.java:558)
00:11:38.838 [Hardware legend.game.scripting.ScriptState:247] INFO : Deallocating script 17 children
00:11:38.838 [Hardware legend.game.scripting.ScriptState:229] INFO : Deallocating script state 17
00:11:38.838 [Hardware legend.game.combat.SEffe:516] INFO : Deallocating effect manager 17
00:11:38.838 [Hardware legend.game.scripting.ScriptState:247] INFO : Deallocating script 21 children
00:11:38.838 [Hardware legend.game.scripting.ScriptState:229] INFO : Deallocating script state 21
00:11:38.838 [Hardware legend.game.combat.SEffe:516] INFO : Deallocating effect manager 21
00:11:38.838 [Hardware legend.game.scripting.ScriptState:247] INFO : Deallocating script 19 children
00:11:38.838 [Hardware legend.game.scripting.ScriptState:229] INFO : Deallocating script state 19
00:11:38.838 [Hardware legend.game.combat.SEffe:516] INFO : Deallocating effect manager 19
00:11:38.838 [Hardware legend.game.scripting.ScriptState:247] INFO : Deallocating script 18 children
00:11:38.838 [Hardware legend.game.scripting.ScriptState:229] INFO : Deallocating script state 18
00:11:38.838 [Hardware legend.game.combat.SEffe:516] INFO : Deallocating effect manager 18
00:11:38.839 [Hardware legend.game.scripting.ScriptState:247] INFO : Deallocating script 22 children
00:11:38.839 [Hardware legend.game.scripting.ScriptState:229] INFO : Deallocating script state 22
00:11:38.839 [Hardware legend.game.combat.SEffe:516] INFO : Deallocating effect manager 22
00:11:38.839 [Hardware legend.game.scripting.ScriptState:247] INFO : Deallocating script 20 children
00:11:38.839 [Hardware legend.game.scripting.ScriptState:229] INFO : Deallocating script state 20
00:11:38.839 [Hardware legend.game.combat.SEffe:516] INFO : Deallocating effect manager 20
00:11:40.385 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 17 (ElectricityEffect38)
00:11:40.385 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Do nothing into index 17 (entry point 0x0)
00:11:40.385 [Hardware legend.game.combat.SEffe:580] INFO : Allocating effect manager 17 for ElectricityEffect38 (parent: 15) from legend.game.combat.SEffe.scriptAllocateElectricityEffect(SEffe.java:997)
00:11:40.385 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script .\files\SECT\DRGN0.BIN\4632 into index 17 (entry point 0x0)
00:11:40.385 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 18 (ElectricityEffect38)
00:11:40.385 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Do nothing into index 18 (entry point 0x0)
00:11:40.385 [Hardware legend.game.combat.SEffe:580] INFO : Allocating effect manager 18 for ElectricityEffect38 (parent: 15) from legend.game.combat.SEffe.scriptAllocateElectricityEffect(SEffe.java:997)
00:11:40.385 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script .\files\SECT\DRGN0.BIN\4632 into index 18 (entry point 0x0)
00:11:40.385 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 19 (ElectricityEffect38)
00:11:40.385 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Do nothing into index 19 (entry point 0x0)
00:11:40.385 [Hardware legend.game.combat.SEffe:580] INFO : Allocating effect manager 19 for ElectricityEffect38 (parent: 15) from legend.game.combat.SEffe.scriptAllocateElectricityEffect(SEffe.java:997)
00:11:40.385 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script .\files\SECT\DRGN0.BIN\4632 into index 19 (entry point 0x0)
00:11:40.437 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 20 (Empty EffectManager child, allocated by script 15 (DEFF ticker for script 12 (Enemy combatant index 1)) from scriptAllocateEmptyEffectManagerChild)
00:11:40.437 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Do nothing into index 20 (entry point 0x0)
00:11:40.437 [Hardware legend.game.combat.SEffe:582] INFO : Allocating empty effect manager 20 (parent: 15) from legend.game.combat.SEffe.allocateEffectManager(SEffe.java:558)
00:11:40.437 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script .\files\SECT\DRGN0.BIN\4632 into index 20 (entry point 0x0)
00:11:40.437 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 21 (Empty EffectManager child, allocated by script 15 (DEFF ticker for script 12 (Enemy combatant index 1)) from scriptAllocateEmptyEffectManagerChild)
00:11:40.437 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Do nothing into index 21 (entry point 0x0)
00:11:40.437 [Hardware legend.game.combat.SEffe:582] INFO : Allocating empty effect manager 21 (parent: 15) from legend.game.combat.SEffe.allocateEffectManager(SEffe.java:558)
00:11:40.437 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script .\files\SECT\DRGN0.BIN\4632 into index 21 (entry point 0x0)
00:11:40.437 [Hardware legend.game.scripting.ScriptState:1198] INFO : Script 15 forking script script[15].stor[28] 0x7 and re-entering at offset script[15].inl[0x4f38] 0x2
00:11:40.437 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 22 (Forked Char ID 4 (bent + 7))
00:11:40.437 [Hardware legend.game.scripting.ScriptState:274] INFO : Forking script 7 to 22 legend.game.scripting.ScriptState.scriptForkAndReenter(ScriptState.java:1201)
00:11:40.437 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 24 (ThunderArrowEffect1c)
00:11:40.437 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Do nothing into index 24 (entry point 0x0)
00:11:40.437 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 25 (ThunderArrowEffect1c)
00:11:40.437 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Do nothing into index 25 (entry point 0x0)
00:11:40.437 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 26 (ThunderArrowEffect1c)
00:11:40.437 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Do nothing into index 26 (entry point 0x0)
00:11:40.437 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 27 (BillboardSpriteEffect0c)
00:11:40.437 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Do nothing into index 27 (entry point 0x0)
00:11:40.437 [Hardware legend.game.combat.SEffe:580] INFO : Allocating effect manager 27 for BillboardSpriteEffect0c (parent: 20) from legend.game.combat.SEffe.allocateEffectManager(SEffe.java:558)
00:11:40.486 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 28 (GuardEffect06)
00:11:40.486 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Do nothing into index 28 (entry point 0x0)
00:11:40.486 [Hardware legend.game.combat.SEffe:580] INFO : Allocating effect manager 28 for GuardEffect06 (parent: 7) from legend.game.combat.SEffe.allocateEffectManager(SEffe.java:558)
00:11:40.487 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 29 (ThunderArrowEffect1c)
00:11:40.487 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Do nothing into index 29 (entry point 0x0)
00:11:40.487 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 30 (ThunderArrowEffect1c)
00:11:40.487 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Do nothing into index 30 (entry point 0x0)
00:11:40.487 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 31 (ThunderArrowEffect1c)
00:11:40.487 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Do nothing into index 31 (entry point 0x0)
00:11:40.487 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 32 (Particle effect fff05)
00:11:40.487 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Do nothing into index 32 (entry point 0x0)
00:11:40.487 [Hardware legend.game.combat.SEffe:580] INFO : Allocating effect manager 32 for QuadParticle (parent: 20) from legend.game.combat.particles.ParticleManager.allocateParticle(ParticleManager.java:52)
00:11:40.495 [Hardware legend.core.opengl.Window:118] INFO : Shutting down...
00:11:40.625 [Hardware legend.game.Main:64] ERROR: ----------------------------------------------------------------------------
00:11:40.625 [Hardware legend.game.Main:65] ERROR: Crash detected
00:11:40.626 [Hardware legend.game.Main:66] ERROR: Severed Chains 3.0.0-SNAPSHOT-beta commit COMMIT built null
00:11:40.626 [Hardware legend.game.Main:72] ERROR: Please copy this crash log and send it to us in the Player Help channel in the Legend of Dragoon Discord server.
00:11:40.626 [Hardware legend.game.Main:73] ERROR: https://discord.gg/legendofdragoon
00:11:40.626 [Hardware legend.game.Main:76] ERROR: Message: Index 0 out of bounds for length 0
00:11:40.626 [Hardware legend.game.Main:79] ERROR: ----------------------------------------------------------------------------
00:11:40.626 [Hardware legend.game.Main:80] ERROR: Stack trace:
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at legend.core.gpu.GpuCommandPoly.render(GpuCommandPoly.java:189)
	at legend.core.gpu.Gpu.tick(Gpu.java:211)
	at legend.core.gpu.Gpu.endFrame(Gpu.java:139)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$46(Scus94491BpeSegment.java:441)
	at legend.core.RenderEngine.lambda$init$21(RenderEngine.java:630)
	at legend.core.opengl.Window$Events.onDraw(Window.java:792)
	at legend.core.opengl.Window.tickFrame(Window.java:432)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:408)
	at legend.core.RenderEngine.run(RenderEngine.java:1029)
	at legend.core.GameEngine.start(GameEngine.java:252)
	at legend.game.Main.main(Main.java:40)
00:11:40.629 [Hardware legend.game.Main:82] ERROR: Please copy this crash log and send it to us in the Player Help channel in the Legend of Dragoon Discord server.
00:11:40.629 [Hardware legend.game.Main:83] ERROR: https://discord.gg/legendofdragoon
Disconnected from the target VM, address: '127.0.0.1:49851', transport: 'socket'

Process finished with exit code 1
```

**Comment by LordMonoxide** [comment]
This was caused by memory corruption, calling `data.transforms.set` instead of `data.transforms.transfer.set`
