### ISSUE TITLE
Crash at end of Zackwell cutscene after Solo'ing

### ISSUE THREAD

**Issue by Chocolate06** [Legend-of-Dragoon-Modding/Severed-Chains#1737]
As Lavitz backs away from Dart and Albert

08:50:38.397 [Hardware legend.game.scripting.ScriptState:1236] ERROR: ScriptState[14] Empty EffectManager child, allocated by script 29 (DEFF ticker for script 11 (Enemy combatant index 0)) from scriptAllocateEmptyEffectManagerChild crashed!
08:50:38.397 [Hardware legend.game.scripting.ScriptState:1237] ERROR: File .\files\SECT\DRGN0.BIN\5608 CALL @ 0xd18
08:50:38.397 [Hardware legend.game.scripting.ScriptState:1238] ERROR: Parameters:
08:50:38.397 [Hardware legend.game.scripting.ScriptState:1239] ERROR:   Op param: 0xa7
08:50:38.398 [Hardware legend.game.scripting.ScriptState:1241] ERROR:   0: script[14].stor[10] 0xffffffff
08:50:38.398 [Hardware legend.game.scripting.ScriptState:1241] ERROR:   1: script[14].stor[9] 0xffffffff
08:50:38.398 [Hardware legend.game.scripting.ScriptState:1244] ERROR: Storage:
08:50:38.398 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   0: 0xe
08:50:38.398 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   1: 0xffffffff
08:50:38.398 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   2: 0xffffffff
08:50:38.399 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   3: 0xffffffff
08:50:38.399 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   4: 0xffffffff
08:50:38.399 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   5: 0xffffffff
08:50:38.399 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   6: 0xffffffff
08:50:38.399 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   7: 0x90000
08:50:38.399 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   8: 0x1
08:50:38.399 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   9: 0xffffffff
08:50:38.399 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   10: 0xffffffff
08:50:38.399 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   11: 0xffffffff
08:50:38.399 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   12: 0xffffffff
08:50:38.400 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   13: 0xffffffff
08:50:38.400 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   14: 0xffffffff
08:50:38.400 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   15: 0xffffffff
08:50:38.400 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   16: 0xffffffff
08:50:38.400 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   17: 0xffffffff
08:50:38.400 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   18: 0xffffffff
08:50:38.400 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   19: 0xffffffff
08:50:38.400 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   20: 0xffffffff
08:50:38.400 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   21: 0xffffffff
08:50:38.400 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   22: 0xffffffff
08:50:38.400 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   23: 0x12
08:50:38.400 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   24: 0xffffffff
08:50:38.400 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   25: 0xffffffff
08:50:38.401 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   26: 0xffffffff
08:50:38.401 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   27: 0xffffffff
08:50:38.401 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   28: 0xffffffff
08:50:38.401 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   29: 0xffffffff
08:50:38.401 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   30: 0xffffffff
08:50:38.401 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   31: 0xffffffff
08:50:38.401 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   32: 0xffffffff
08:50:38.401 [Hardware legend.game.scripting.ScriptState:1249] ERROR: Registry IDs:
08:50:38.401 [Hardware legend.game.scripting.ScriptState:1256] ERROR: Call stack:
08:50:38.401 [Hardware legend.game.scripting.ScriptState:1258] ERROR:   0: .\files\SECT\DRGN0.BIN\5608 0xd0c
08:50:38.401 [Hardware legend.game.scripting.ScriptState:1261] ERROR: Disassembly:
08:50:38.450 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   ce0: mov 0x29, stor[stor[stor[0], 23], 14] ; source, dest
08:50:38.450 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   cec: mov 0x1, stor[stor[stor[0], 23], 24] ; source, dest
08:50:38.450 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   cf8: call SEffe::scriptLoadSameScriptAndJump, stor[23], inl[:LABEL_102] ; scriptIndex, address
08:50:38.450 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   d04: gosub inl[:LABEL_100] ; addr
08:50:38.450 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   d0c: mov var[34][1], stor[10] ; source, dest
08:50:38.451 [Hardware legend.game.scripting.ScriptState:1284] ERROR:   d18: call Battle::scriptGetCharOrMonsterId, stor[10], stor[9] ; bentIndex, id
08:50:38.451 [Hardware legend.game.scripting.ScriptState:1285] ERROR:   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
08:50:38.451 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   d24: jmp_cmp ==, 0x5, stor[9], inl[:LABEL_9] ; operand, left, right, addr
08:50:38.451 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   d34: mov var[34][2], stor[10] ; source, dest
08:50:38.451 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   d40: call Battle::scriptGetCharOrMonsterId, stor[10], stor[9] ; bentIndex, id
08:50:38.451 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   d4c: jmp_cmp ==, 0x5, stor[9], inl[:LABEL_9] ; operand, left, right, addr
08:50:38.451 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   LABEL_16:
08:50:38.452 [Hardware legend.core.RenderEngine:1133] ERROR: Shutting down due to exception:
java.lang.RuntimeException: An error occurred while ticking script 14
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:203)
        at legend.game.scripting.ScriptManager.tick(ScriptManager.java:61)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:423)
        at legend.core.RenderEngine.lambda$init$17(RenderEngine.java:504)
        at legend.core.opengl.Window$Events.onDraw(Window.java:697)
        at legend.core.opengl.Window.tickFrame(Window.java:337)
        at legend.core.opengl.Action.run(Action.java:46)
        at legend.core.opengl.Action.tick(Action.java:32)
        at legend.core.opengl.Window.run(Window.java:314)
        at legend.core.RenderEngine.run(RenderEngine.java:1131)
        at legend.core.GameEngine.start(GameEngine.java:251)
        at legend.game.Main.main(Main.java:24)
        at legend.game.MainWindows.main(MainWindows.java:33)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 108
        at legend.game.combat.Battle.scriptGetCharOrMonsterId(Battle.java:3485)
        at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:1029)
        at legend.game.scripting.ScriptState.runOp(ScriptState.java:623)
        at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:410)
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:199)
        ... 12 more

**Comment by Chocolate06** [comment]
Also true for 2 person party
