### ISSUE TITLE
Melbu crash

### ISSUE THREAD

**Issue by Chocolate06** [Legend-of-Dragoon-Modding/Severed-Chains#1739]
First phase, using Rose and Dart, just threw the Psyche Bomb X with Rose

14:10:20.686 [Hardware legend.game.scripting.ScriptState:1236] ERROR: ScriptState[19] Empty EffectManager child, allocated by script 17 (Empty EffectManager child, allocated by script 16 (DEFF ticker for script 11 (Enemy combatant index 0)) from scriptAllocateEmptyEffectManagerChild) from scriptAllocateEmptyEffectManagerChild crashed!
14:10:20.687 [Hardware legend.game.scripting.ScriptState:1237] ERROR: File .\files\SECT\DRGN0.BIN\5418 CALL @ 0x23f8
14:10:20.688 [Hardware legend.game.scripting.ScriptState:1238] ERROR: Parameters:
14:10:20.689 [Hardware legend.game.scripting.ScriptState:1239] ERROR:   Op param: 0x84
14:10:20.690 [Hardware legend.game.scripting.ScriptState:1241] ERROR:   0: script[19].stor[28] 0xffffffff
14:10:20.691 [Hardware legend.game.scripting.ScriptState:1241] ERROR:   1: script[19].inl[0x2400] 0x500
14:10:20.692 [Hardware legend.game.scripting.ScriptState:1244] ERROR: Storage:
14:10:20.692 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   0: 0x13
14:10:20.693 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   1: 0xffffffff
14:10:20.693 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   2: 0xffffffff
14:10:20.693 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   3: 0xffffffff
14:10:20.693 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   4: 0xffffffff
14:10:20.693 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   5: 0xffffffff
14:10:20.693 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   6: 0xffffffff
14:10:20.694 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   7: 0x90000
14:10:20.694 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   8: 0xffffffff
14:10:20.695 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   9: 0xffffffff
14:10:20.695 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   10: 0xffffffff
14:10:20.697 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   11: 0xffffffff
14:10:20.697 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   12: 0xffffffff
14:10:20.697 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   13: 0xffffffff
14:10:20.697 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   14: 0xffffffff
14:10:20.697 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   15: 0xffffffff
14:10:20.698 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   16: 0xffffffff
14:10:20.698 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   17: 0xffffffff
14:10:20.698 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   18: 0xffffffff
14:10:20.698 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   19: 0xffffffff
14:10:20.699 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   20: 0xffffffff
14:10:20.699 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   21: 0xffffffff
14:10:20.699 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   22: 0xffffffff
14:10:20.699 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   23: 0xffffffff
14:10:20.699 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   24: 0xffffffff
14:10:20.700 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   25: 0xffffffff
14:10:20.700 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   26: 0xffffffff
14:10:20.700 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   27: 0xffffffff
14:10:20.703 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   28: 0xffffffff
14:10:20.704 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   29: 0xffffffff
14:10:20.704 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   30: 0xffffffff
14:10:20.704 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   31: 0xffffffff
14:10:20.705 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   32: 0xffffffff
14:10:20.708 [Hardware legend.game.scripting.ScriptState:1249] ERROR: Registry IDs:
14:10:20.708 [Hardware legend.game.scripting.ScriptState:1256] ERROR: Call stack:
14:10:20.709 [Hardware legend.game.scripting.ScriptState:1258] ERROR:   0: .\files\SECT\DRGN0.BIN\5418 0x23c8
14:10:20.710 [Hardware legend.game.scripting.ScriptState:1261] ERROR: Disassembly:
14:10:20.740 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   LABEL_62:
14:10:20.742 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   23c8: call Battle::scriptSetCameraProjectionPlaneDistance, 0x140 ; distance
14:10:20.742 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   23d0: mov var[34][1], stor[28] ; source, dest
14:10:20.742 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   23dc: call Battle::scriptSetBentRotationY, stor[28], 0x300 ; bentIndex, y
14:10:20.742 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   23ec: mov var[34][2], stor[28] ; source, dest
14:10:20.742 [Hardware legend.game.scripting.ScriptState:1284] ERROR:   23f8: call Battle::scriptSetBentRotationY, stor[28], 0x500 ; bentIndex, y
14:10:20.742 [Hardware legend.game.scripting.ScriptState:1285] ERROR:   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
14:10:20.742 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   2404: gosub inl[:LABEL_17] ; addr
14:10:20.743 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   240c: call Battle::scriptAllocateEmptyEffectManagerChild, stor[18] ; effectIndex
14:10:20.743 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   2414: call SEffe::scriptSetRelativePosition, stor[18], stor[28], 0x428, 0xfffff5d9, 0xab8 ; bobjIndex1, bobjIndex2, x, y, z
14:10:20.743 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   2430: call SEffe::scriptGetRelativePosition, stor[18], 0xffffffff, stor[24], stor[25], stor[26] ; bobjIndex, parentIndex, x, y, z
14:10:20.743 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   244c: shl 0x8, stor[24] ; shift, val
14:10:20.743 [Hardware legend.core.RenderEngine:1133] ERROR: Shutting down due to exception:
java.lang.RuntimeException: An error occurred while ticking script 19
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:203)
        at legend.game.scripting.ScriptManager.tick(ScriptManager.java:61)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:423)
        at legend.core.RenderEngine.lambda$init$17(RenderEngine.java:504)
        at legend.core.opengl.Window$Events.onDraw(Window.java:697)
        at legend.core.opengl.Window.tickFrame(Window.java:337)
        at legend.core.opengl.Action.run(Action.java:46)
        at legend.core.opengl.Action.tick(Action.java:32)
        at legend.core.opengl.Window.run(Window.java:314)
        at legend.core.RenderEngine.run(RenderEngine.java:1131)
        at legend.core.GameEngine.start(GameEngine.java:251)
        at legend.game.Main.main(Main.java:24)
        at legend.game.MainWindows.main(MainWindows.java:33)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 108
        at legend.game.combat.Battle.scriptSetBentRotationY(Battle.java:2783)
        at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:1029)
        at legend.game.scripting.ScriptState.runOp(ScriptState.java:623)
        at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:410)
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:199)
        ... 12 more

**Comment by Chocolate06** [comment]
Probably not specific to the Psyche Bomb X, used it successfully afterwards in a party of 2
