### ISSUE TITLE
Icarus forgot a comma

### ISSUE THREAD

**Issue by Chocolate06** [Legend-of-Dragoon-Modding/Severed-Chains#1769]
Exception in thread "Thread-2" java.lang.RuntimeException: java.lang.RuntimeException: Unknown param == 0x1
        at legend.core.GameEngine.lambda$start$8(GameEngine.java:230)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: Unknown param == 0x1
        at org.legendofdragoon.scripting.Lexer.parseParam(Lexer.java:547)
        at org.legendofdragoon.scripting.Lexer.parseParams(Lexer.java:289)
        at org.legendofdragoon.scripting.Lexer.lexLine(Lexer.java:258)
        at org.legendofdragoon.scripting.Lexer.lex(Lexer.java:115)
        at legend.game.scripting.ScriptManager.compile(ScriptManager.java:269)
        at legend.game.unpacker.scripts.ScriptPatcher.recompile(ScriptPatcher.java:240)
        at legend.game.unpacker.scripts.ScriptPatcher.patchFile(ScriptPatcher.java:191)
        at legend.game.unpacker.scripts.ScriptPatcher.patchFile(ScriptPatcher.java:177)
        at legend.game.unpacker.scripts.ScriptPatcher.patchFile(ScriptPatcher.java:168)
        at legend.game.unpacker.scripts.ScriptPatcher.apply(ScriptPatcher.java:136)
        at legend.core.GameEngine.lambda$start$8(GameEngine.java:222)
        ... 1 more

**Comment by avionanx** [comment]
closed by #1770
