### ISSUE TITLE
Char Swap Screen Crash

### ISSUE THREAD

**Issue by avionanx** [Legend-of-Dragoon-Modding/Severed-Chains#1773]
```
19:50:04.335 [Hardware legend.core.RenderEngine:1133] ERROR: Shutting down due to exception:
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 9
	at legend.game.inventory.screens.CharSwapScreen.mouseMove(CharSwapScreen.java:151)
	at legend.game.inventory.screens.MenuStack.lambda$mouseMove$1(MenuStack.java:172)
	at legend.game.inventory.screens.MenuStack.propagate(MenuStack.java:116)
	at legend.game.inventory.screens.MenuStack.input(MenuStack.java:108)
	at legend.game.inventory.screens.MenuStack.mouseMove(MenuStack.java:172)
	at legend.core.opengl.Window$Events.lambda$onMouseMove$7(Window.java:462)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at legend.core.opengl.Window$Events.onMouseMove(Window.java:462)
	at org.lwjgl.glfw.GLFWCursorPosCallbackI.callback(GLFWCursorPosCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at legend.core.opengl.Window.tickInput(Window.java:331)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:314)
	at legend.core.RenderEngine.run(RenderEngine.java:1131)
	at legend.core.GameEngine.start(GameEngine.java:251)
	at legend.game.Main.main(Main.java:24)
```

**Comment by LordMonoxide** [comment]
Closed by 12d3fa341f207277cb319a054a4710b6f8cbf1fb
