### ISSUE TITLE
Crash after Fruegal 2

### ISSUE THREAD

**Issue by dongputer** [Legend-of-Dragoon-Modding/Severed-Chains#1789]
After battle, before the cutscene.

22:49:34.956 [Hardware legend.game.scripting.ScriptManager:129] ERROR: Script 15 crashed!
22:49:34.956 [Hardware legend.game.scripting.ScriptManager:130] ERROR: File 5518/1[1624]
22:49:34.957 [Hardware legend.game.scripting.ScriptManager:131] ERROR: Parameters:
22:49:34.957 [Hardware legend.game.scripting.ScriptManager:132] ERROR:   Op param: 0x142
22:49:34.957 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   1: script[15].storage[12] 7
22:49:34.957 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   2: script[0x67e] 0x1
22:49:34.957 [Hardware legend.game.scripting.ScriptManager:137] ERROR: Storage:
22:49:34.957 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   1: 0xf
22:49:34.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   2: 0xffffffff
22:49:34.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   3: 0xffffffff
22:49:34.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   4: 0xffffffff
22:49:34.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   5: 0xffffffff
22:49:34.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   6: 0xffffffff
22:49:34.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   7: 0xffffffff
22:49:34.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   8: 0x90000
22:49:34.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   9: 0x0
22:49:34.959 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   10: 0x96
22:49:34.959 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   11: 0x3
22:49:34.959 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   12: 0xffffffff
22:49:34.959 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   13: 0x7
22:49:34.959 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   14: 0xffffffff
22:49:34.959 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   15: 0xffffffff
22:49:34.959 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   16: 0xffffffff
22:49:34.960 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   17: 0xffffffff
22:49:34.960 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   18: 0xffffffff
22:49:34.960 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   19: 0xffffffff
22:49:34.960 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   20: 0xffffffff
22:49:34.960 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   21: 0xffffffff
22:49:34.960 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   22: 0xffffffff
22:49:34.960 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   23: 0xffffffff
22:49:34.961 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   24: 0xd
22:49:34.961 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   25: 0xffffffff
22:49:34.961 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   26: 0xffffffff
22:49:34.961 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   27: 0xffffffff
22:49:34.961 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   28: 0xb
22:49:34.961 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   29: 0xffffffff
22:49:34.961 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   30: 0xffffffff
22:49:34.961 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   31: 0xffffffff
22:49:34.961 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   32: 0xffffffff
22:49:34.961 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   33: 0xffffffff
22:49:34.962 [Hardware legend.game.scripting.ScriptManager:142] ERROR: Call stack:
22:49:34.962 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   1: 58
22:49:34.962 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   2: 0
22:49:34.962 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   3: 0
22:49:34.962 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   4: 0
22:49:34.962 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   5: 0
22:49:34.962 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   6: 0
22:49:34.962 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   7: 0
22:49:34.962 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   8: 0
22:49:34.962 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   9: 0
22:49:34.963 [Hardware legend.core.gpu.Gpu:148] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: An error occurred while ticking script 15
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:151)
        at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
        at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:596)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:514)
        at legend.core.gpu.Gpu.lambda$setStandardRenderer$4(Gpu.java:272)
        at legend.core.gpu.Gpu.lambda$init$3(Gpu.java:222)
        at legend.core.opengl.Context.draw(Context.java:91)
        at legend.core.opengl.Window$Events.onDraw(Window.java:653)
        at legend.core.opengl.Window.tickFrame(Window.java:294)
        at legend.core.opengl.Action.run(Action.java:46)
        at legend.core.opengl.Action.tick(Action.java:32)
        at legend.core.opengl.Window.run(Window.java:271)
        at legend.core.gpu.Gpu.run(Gpu.java:146)
        at legend.core.GameEngine.start(GameEngine.java:225)
        at legend.game.Main.main(Main.java:23)
        at legend.game.MainWindows.main(MainWindows.java:33)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 16
        at legend.game.Scus94491BpeSegment_8002.applyModelPartTransforms(Scus94491BpeSegment_8002.java:686)
        at legend.game.Scus94491BpeSegment_8002.loadModelStandardAnimation(Scus94491BpeSegment_8002.java:744)
        at legend.game.combat.Bttl_800c.FUN_800ca100(Bttl_800c.java:1995)
        at legend.game.combat.Bttl_800c.FUN_800cb84c(Bttl_800c.java:2661)
        at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:904)
        at legend.game.scripting.ScriptState.runOp(ScriptState.java:540)
        at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:468)
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:125)

**Comment by LordMonoxide** [comment]
What build are you using? 2.1 or the devbuild?

**Comment by dongputer** [comment]
2.1

**Comment by LordMonoxide** [comment]
Are you using nodart?

**Comment by dongputer** [comment]
I had used it earlier in the playthough. I turned unlock party back to false and made sure he was in slot 1.

**Comment by LordMonoxide** [comment]
Closing as this has already been fixed in the devbuilds
