### ISSUE TITLE
game crash 

### ISSUE THREAD

**Issue by Jaredlamphere55** [Legend-of-Dragoon-Modding/Severed-Chains#1805]
every time I'm crossing the garbage bridge to collect the red stone the game crashes. here are the full error:

19:16:39.955 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   2: script[10].storage[30] 1
19:16:39.956 [Hardware legend.game.scripting.ScriptManager:137] ERROR: Storage:
19:16:39.962 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   1: 0xa
19:16:39.962 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   2: 0xffffffff
19:16:39.962 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   3: 0xffffffff
19:16:39.962 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   4: 0xffffffff
19:16:39.980 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   5: 0xffffffff
19:16:39.980 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   6: 0xffffffff
19:16:39.980 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   7: 0xffffffff
19:16:39.980 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   8: 0x10000
19:16:39.980 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   9: 0xfffffe87
19:16:39.980 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   10: 0x1
19:16:39.981 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   11: 0xffffff8c
19:16:39.981 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   12: 0xffffffff
19:16:39.981 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   13: 0xffffffff
19:16:39.981 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   14: 0xffffffff
19:16:39.981 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   15: 0xffffffff
19:16:39.981 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   16: 0xffffffff
19:16:39.982 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   17: 0xffffffff
19:16:39.982 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   18: 0xffffffff
19:16:39.982 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   19: 0xffffffff
19:16:39.982 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   20: 0xffffffff
19:16:39.982 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   21: 0xffffffff
19:16:39.982 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   22: 0xffffffff
19:16:39.983 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   23: 0xffffffff
19:16:39.983 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   24: 0x0
19:16:39.983 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   25: 0x10
19:16:39.983 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   26: 0x0
19:16:39.983 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   27: 0x0
19:16:39.984 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   28: 0x0
19:16:39.984 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   29: 0x105
19:16:39.984 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   30: 0xa000
19:16:39.984 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   31: 0x1
19:16:39.984 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   32: 0x29
19:16:39.984 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   33: 0xffffffff
19:16:39.985 [Hardware legend.game.scripting.ScriptManager:142] ERROR: Call stack:
19:16:39.989 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   1: 1033
19:16:39.989 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   2: 768
19:16:39.989 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   3: 0
19:16:39.989 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   4: 0
19:16:39.989 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   5: 0
19:16:39.990 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   6: 0
19:16:39.990 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   7: 0
19:16:39.990 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   8: 0
19:16:39.990 [Hardware legend.core.gpu.Gpu:148] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: An error occurred while ticking script 10
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:151)
        at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
        at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:596)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:514)
        at legend.core.gpu.Gpu.lambda$setStandardRenderer$4(Gpu.java:272)
        at legend.core.gpu.Gpu.lambda$init$3(Gpu.java:222)
        at legend.core.opengl.Context.draw(Context.java:91)
        at legend.core.opengl.Window$Events.onDraw(Window.java:653)
        at legend.core.opengl.Window.tickFrame(Window.java:294)
        at legend.core.opengl.Action.run(Action.java:46)
        at legend.core.opengl.Action.tick(Action.java:32)
        at legend.core.opengl.Window.run(Window.java:271)
        at legend.core.gpu.Gpu.run(Gpu.java:146)
        at legend.core.GameEngine.start(GameEngine.java:225)
        at legend.game.Main.main(Main.java:23)
        at legend.game.MainWindows.main(MainWindows.java:33)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2535 out of bounds for length 2535
        at legend.game.scripting.ScriptFile.getOp(ScriptFile.java:25)
        at legend.game.scripting.ScriptInlineParam.get(ScriptInlineParam.java:26)
        at legend.game.scripting.ScriptState.scriptMove(ScriptState.java:649)
        at legend.game.scripting.ScriptState.runOp(ScriptState.java:502)
        at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:468)
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:125)
        ... 15 more
19:16:39.991 [Hardware legend.core.opengl.Window:93] INFO : Shutting down...

**Comment by Chocolate06** [comment]
What build are you using? I believe this is already fixed on current devbuilds.

**Comment by Jaredlamphere55** [comment]
im using the current stable build can i move my save and reinstall would that be a possible fix

**Comment by Chocolate06** [comment]
saves are forward compatible, you can just drag/copy your save folder to the new SC folder

**Comment by theflyingzamboni** [comment]
@Jaredlamphere55 What chocolate said, just download the devbuild here: https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/releases/tag/devbuild

Copy your discs and saves over to the new install and everything will just work.

Closing this as an old bug.
