### ISSUE TITLE
Crash - wisp using spell on phantom ship

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Severed-Chains#1825]
Whatever the spell is with the 5 pools of fire

```
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1236] ERROR: ScriptState[15] DEFF ticker for script 13 (Enemy combatant index 2) crashed!
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1237] ERROR: File .\files\SECT\DRGN0.BIN\4342 CALL @ 0x37c
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1238] ERROR: Parameters:
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1239] ERROR:   Op param: 0xa8
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1241] ERROR:   0: script[15].stor[30] 0xd
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1241] ERROR:   1: script[15].stor[8] 0x11
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1241] ERROR:   2: script[15].inl[0x388] 0x27
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1244] ERROR: Storage:
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   0: 0xf
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   1: 0xffffffff
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   2: 0xffffffff
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   3: 0xffffffff
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   4: 0xffffffff
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   5: 0xffffffff
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   6: 0xffffffff
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   7: 0x10000
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   8: 0x11
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   9: 0xe
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   10: 0x5
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   11: 0x0
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   12: 0x0
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   13: 0x64
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   14: 0x18
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   15: 0x18
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   16: 0x12
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   17: 0x1f
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   18: 0x11
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   19: 0xffffffff
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   20: 0xffffffff
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   21: 0xffffffff
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   22: 0x15
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   23: 0x0
22:30:42.680 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   24: 0xffffffea
22:30:42.681 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   25: 0x0
22:30:42.681 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   26: 0x2
22:30:42.681 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   27: 0x11
22:30:42.681 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   28: 0x8
22:30:42.681 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   29: 0x0
22:30:42.681 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   30: 0xd
22:30:42.681 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   31: 0x15
22:30:42.681 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   32: 0xffffffff
22:30:42.681 [Hardware legend.game.scripting.ScriptState:1249] ERROR: Registry IDs:
22:30:42.681 [Hardware legend.game.scripting.ScriptState:1256] ERROR: Call stack:
22:30:42.681 [Hardware legend.game.scripting.ScriptState:1258] ERROR:   0: .\files\SECT\DRGN0.BIN\4342 0x354
22:30:42.681 [Hardware legend.game.scripting.ScriptState:1258] ERROR:   1: .\files\SECT\DRGN0.BIN\4342 0x1bf0
22:30:42.681 [Hardware legend.game.scripting.ScriptState:1258] ERROR:   2: .\files\SECT\DRGN0.BIN\4342 0x33c4
22:30:42.681 [Hardware legend.game.scripting.ScriptState:1261] ERROR: Disassembly:
22:30:42.713 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   ; SUBROUTINE
22:30:42.713 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   LABEL_0:
22:30:42.713 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   354: call Battle::scriptGetBentSlot, stor[28], stor[10], 0x0 ; bentIndex, charOrBentSlot, mode
22:30:42.713 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   364: mov stor[8], var[128 + stor[10]][5] ; source, dest
22:30:42.713 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   370: mov 0x3, var[128 + stor[10]][0] ; source, dest
22:30:42.713 [Hardware legend.game.scripting.ScriptState:1284] ERROR:   37c: call Battle::scriptSetBentStat, stor[30], stor[8], ITEM_ID ; bentIndex, value, statIndex
22:30:42.713 [Hardware legend.game.scripting.ScriptState:1285] ERROR:   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
22:30:42.713 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   38c: mov stor[8], var[45][119] ; source, dest
22:30:42.713 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   398: call Battle::scriptSetTempItemMagicStats, stor[30] ; bentIndex
22:30:42.713 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   3a0: call Battle::scriptCheckItemHit, stor[30], stor[28], stor[9] ; attackerIndex, defenderIndex, hit
22:30:42.713 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   3b0: jmp_cmp ==, 0x0, stor[9], inl[:LABEL_2] ; operand, left, right, addr
22:30:42.713 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   3bc: call Battle::scriptItemMagicAttack, stor[30], stor[28], stor[8], stor[8], stor[10] ; attackerIndex, defenderIndex, unused, damage, specialEffects
22:30:52.730 [SFX legend.game.Scus94491BpeSegment:475] WARN : Sequencer running behind, skipping ticks to catch up
22:30:52.731 [Hardware legend.core.RenderEngine:971] ERROR: Shutting down due to exception:
java.lang.RuntimeException: An error occurred while ticking script 15
	at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:203)
	at legend.game.scripting.ScriptManager.tick(ScriptManager.java:61)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:410)
	at legend.core.RenderEngine.lambda$init$21(RenderEngine.java:579)
	at legend.core.opengl.Window$Events.onDraw(Window.java:701)
	at legend.core.opengl.Window.tickFrame(Window.java:341)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:318)
	at legend.core.RenderEngine.run(RenderEngine.java:969)
	at legend.core.GameEngine.start(GameEngine.java:248)
	at legend.game.Main.main(Main.java:24)
Caused by: java.lang.IllegalStateException: Registry IDs can't be stored in ScriptStorageParam
	at legend.game.scripting.Param.getRegistryId(Param.java:23)
	at legend.game.combat.Battle.scriptSetBentStat(Battle.java:3509)
	at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:1029)
	at legend.game.scripting.ScriptState.runOp(ScriptState.java:623)
	at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:410)
	at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:199)
	... 11 more
22:30:52.735 [Hardware legend.core.opengl.Window:104] INFO : Shutting down...
```

**Comment by LordMonoxide** [comment]
This seems to only happen on an older build, verified that there is a patch and it's applied. Did not crash during the Livstream.
