### ISSUE TITLE
Frame Advance (Hold) Crashes

### ISSUE THREAD

**Issue by Ink230** [Legend-of-Dragoon-Modding/Severed-Chains#1866]
F11 - Pause
F10 - Hold to frame advance

SC will crash.

```
20:50:27.998 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Submap object 1 (DRGN1/54/2) into index 11 (entry point 0x0)
20:50:27.998 [Hardware legend.game.Scus94491BpeSegment_8002:307] INFO : Loading scripted TMD legend.game.types.CContainer@528e5e38 (animation legend.game.types.TmdAnimationFile@16391278)
20:50:28.000 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 12 (Submap object 2 (file 66))
20:50:28.000 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Submap object 2 (DRGN1/54/3) into index 12 (entry point 0x0)
20:50:28.000 [Hardware legend.game.Scus94491BpeSegment_8002:307] INFO : Loading scripted TMD legend.game.types.CContainer@621dc63d (animation legend.game.types.TmdAnimationFile@4ae49387)
20:50:28.001 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 13 (Submap object 3 (file 99))
20:50:28.001 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Submap object 3 (DRGN1/54/4) into index 13 (entry point 0x0)
20:50:28.001 [Hardware legend.game.Scus94491BpeSegment_8002:307] INFO : Loading scripted TMD legend.game.types.CContainer@6abb7b7d (animation legend.game.types.TmdAnimationFile@34cf0e80)
20:50:28.002 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 14 (Submap object 4 (file 132))
20:50:28.002 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script Submap object 4 (DRGN1/54/5) into index 14 (entry point 0x0)
20:50:28.002 [Hardware legend.game.Scus94491BpeSegment_8002:307] INFO : Loading scripted TMD legend.game.types.CContainer@38ef1a0a (animation legend.game.types.TmdAnimationFile@56f9de3b)
20:50:28.004 [Hardware legend.game.unpacker.Unpacker:164] INFO : Loading file .\files\SUBMAP\alert.tim
20:50:32.243 [Hardware legend.core.RenderEngine:982] ERROR: Shutting down due to exception:
java.lang.ArrayIndexOutOfBoundsException: Index 100 out of bounds for length 100
	at legend.core.opengl.ScissorStack.push(ScissorStack.java:39)
	at legend.game.submap.RetailSubmap.preDraw(RetailSubmap.java:1069)
	at legend.game.submap.SMap.renderSubmap(SMap.java:3243)
	at legend.game.submap.SMap.loadAndRenderSubmapModelAndEffects(SMap.java:3407)
	at legend.game.submap.SMap.tick(SMap.java:3824)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$46(Scus94491BpeSegment.java:406)
	at legend.core.RenderEngine.lambda$init$21(RenderEngine.java:574)
	at legend.core.opengl.Window$Events.onDraw(Window.java:707)
	at legend.core.opengl.Window.tickFrame(Window.java:347)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:324)
	at legend.core.RenderEngine.run(RenderEngine.java:980)
	at legend.core.GameEngine.start(GameEngine.java:248)
	at legend.game.Main.main(Main.java:29)
20:50:32.245 [Hardware legend.core.opengl.Window:106] INFO : Shutting down...
```

Doesn't seem to crash at title/game screens.

**Comment by theflyingzamboni** [comment]
I've used this a lot in combat and it's never crashed there for me. Submap issue only?
