### ISSUE TITLE
Crash after killing Urobolus

### ISSUE THREAD

**Issue by francescogallotta** [Legend-of-Dragoon-Modding/Severed-Chains#1892]
game crashes after killing Urobolus

`01:21:42.400 [Hardware legend.game.Scus94491BpeSegment:861] INFO : Loading DRGN0 2 from legend.game.Scus94491BpeSegment.loadDrgnFile(Scus94491BpeSegment.java:848)
01:21:42.400 [Hardware legend.game.unpacker.Unpacker:195] INFO : Queueing file SECT/DRGN0.BIN/2 (total queued: 1)
01:21:42.400 [pool-2-thread-9 legend.game.unpacker.Unpacker:164] INFO : Loading file .\files\SECT\DRGN0.BIN\2
01:21:42.405 [pool-2-thread-9 legend.game.unpacker.Unpacker:199] INFO : File SECT/DRGN0.BIN/2 loaded (remaining queued: 0)
01:21:42.499 [Hardware legend.game.scripting.ScriptManager:169] INFO : Allocating script index 15 (Bent allocated by script 14)
01:21:42.499 [Hardware legend.game.scripting.ScriptState:215] INFO : Loading script .\files\SECT\DRGN0.BIN\5572 into index 15 (entry point 0x1)
01:21:42.500 [Hardware legend.core.RenderEngine:982] ERROR: Shutting down due to exception:
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
        at legend.game.combat.bent.BattleEntity27c.bentLoadingTicker(BattleEntity27c.java:585)
        at legend.game.scripting.ScriptState.tick(ScriptState.java:191)
        at legend.game.scripting.ScriptManager.executeScriptTickers(ScriptManager.java:224)
        at legend.game.scripting.ScriptManager.tick(ScriptManager.java:70)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$46(Scus94491BpeSegment.java:414)
        at legend.core.RenderEngine.lambda$init$21(RenderEngine.java:599)
        at legend.core.opengl.Window$Events.onDraw(Window.java:707)
        at legend.core.opengl.Window.tickFrame(Window.java:347)
        at legend.core.opengl.Action.run(Action.java:46)
        at legend.core.opengl.Action.tick(Action.java:32)
        at legend.core.opengl.Window.run(Window.java:324)
        at legend.core.RenderEngine.run(RenderEngine.java:980)
        at legend.core.GameEngine.start(GameEngine.java:248)
        at legend.game.Main.main(Main.java:29)
        at legend.game.MainWindows.main(MainWindows.java:38)
01:21:42.501 [Hardware legend.core.opengl.Window:106] INFO : Shutting down...`

**Comment by LordMonoxide** [comment]
@avionanx this is somehow due to the vram slot changes

@francescogallotta temporary fix:
Open `/patches/scripts.csv` and remove the line that says Urobolus. This removes the NoDart fix for this fight so you will have to use the vanilla party (Dart+Lavitz+Shana).
![image](https://github.com/user-attachments/assets/9d8d25a6-5ce2-403a-a1ad-c99ecde82cca)

**Comment by LordMonoxide** [comment]
I've pushed a temporary fix that will cause some texture corruption but prevent the crash

**Comment by LordMonoxide** [comment]
It's crashing because of this flow:
- vram slot is set to :CHAR_INDEX
- texture is loaded
- vram slot is set to -1
- bent model finishes loading, tries to use vram slot to remap model UVs but vram slot is -1

**Comment by Brontis** [comment]
I believe this is happening after the Kongol fight in Hoax as well.

**Comment by LordMonoxide** [comment]
@Brontis I just reverted the changes that caused this, please update to the latest build.

**Comment by Brontis** [comment]
@LordMonoxide You are absolutely amazing, thank you so much!
