### ISSUE TITLE
sssq becomes null when using speed multiplier

### ISSUE THREAD

**Issue by Zychronix** [Legend-of-Dragoon-Modding/Severed-Chains#722]
It seems sssq will randomly become null when running the game at faster speeds and will soft lock the game.
The issue happened twice on 5x speed but still waiting for it to happen on 16x.

Exception in thread "pool-2-thread-26" java.lang.NullPointerException: Cannot invoke "legend.game.sound.Sssq.reader()" because "sssq" is null
	at legend.game.Scus94491BpeSegment_8004.loadSssq(Scus94491BpeSegment_8004.java:1039)
	at legend.game.Scus94491BpeSegment.FUN_8001ddd8(Scus94491BpeSegment.java:2999)
	at legend.game.Scus94491BpeSegment.FUN_8001fb44(Scus94491BpeSegment.java:3643)
	at legend.game.Scus94491BpeSegment.lambda$loadEncounterMusic$66(Scus94491BpeSegment.java:2929)
	at legend.game.unpacker.Unpacker.lambda$loadDirectory$5(Unpacker.java:177)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "pool-2-thread-27" java.lang.UnsupportedOperationException
	at legend.game.sound.SssqReader.baseVolume(SssqReader.java:9)
	at legend.game.Scus94491BpeSegment_8004.setSequenceVolume(Scus94491BpeSegment_8004.java:1177)
	at legend.game.Scus94491BpeSegment.encounterSoundEffectsLoaded(Scus94491BpeSegment.java:3671)
	at legend.game.unpacker.Unpacker.lambda$loadDirectory$5(Unpacker.java:177)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by LordMonoxide** [comment]
@Illeprih assigning this to you, close if it should be fixed by your new music engine
