### ISSUE TITLE
If you press buttons too fast in the load game screen, the menu doesn't unload correctly

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Severed-Chains#756]
The selector wrapping does not appear to be functioning.

```
Cannot invoke "legend.game.types.UiFile.uiElements_0000()" because "legend.game.Scus94491BpeSegment_800b.uiFile_800bdc3c" is null
	at legend.game.Scus94491BpeSegment_8002.allocateManualRenderable(Scus94491BpeSegment_8002.java:1415)
	at legend.game.inventory.screens.controls.DragoonSpirits.setSpirits(DragoonSpirits.java:23)
	at legend.game.inventory.screens.controls.SaveCard.setSaveData(SaveCard.java:51)
	at legend.game.inventory.screens.CampaignSelectionScreen.lambda$new$0(CampaignSelectionScreen.java:50)
	at legend.game.inventory.screens.controls.BigList.highlight(BigList.java:127)
	at legend.game.inventory.screens.controls.BigList.pressedWithRepeatPulse(BigList.java:201)
	at legend.game.inventory.screens.MenuScreen.pressedWithRepeatPulse(MenuScreen.java:140)
	at legend.game.inventory.screens.MenuStack.lambda$pressedWithRepeatPulse$7(MenuStack.java:223)
	at legend.game.inventory.screens.MenuStack.propagate(MenuStack.java:108)
	at legend.game.inventory.screens.MenuStack.input(MenuStack.java:100)
	at legend.game.inventory.screens.MenuStack.pressedWithRepeatPulse(MenuStack.java:223)
	at legend.core.opengl.Window$Events.lambda$onInputPressedWithRepeat$13(Window.java:469)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at legend.core.opengl.Window$Events.onInputPressedWithRepeat(Window.java:469)
	at legend.core.opengl.Window$Events.callInputEvents(Window.java:477)
	at legend.game.input.Input.update(Input.java:63)
	at legend.core.opengl.Window.tickInput(Window.java:306)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:288)
	at legend.core.RenderEngine.run(RenderEngine.java:635)
	at legend.core.GameEngine.start(GameEngine.java:230)
	at legend.game.Main.main(Main.java:23)
```

**Comment by theflyingzamboni** [comment]
I triggered this multiple times, but I can no longer seem to replicate it, despite being on the same commit.
